### ISSUE TITLE
Multiple avro schema support

### ISSUE THREAD

**Issue by michaelpro1** [asyncapi/avro-schema-parser#9]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement?
Typically `.avsc` are broken down into multiple files that will contain various types however they lack import ability of the schemas. Typically compiler processes a whole folder of schemas.
This makes it hard to import multiple schemas into single `async.yaml` file by forcing manual inlining of those schemas
- How will this change help?
Explicit references to used schemas
- What is the motivation? 
Simplify working with avro schemas from the interface

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Potentially the $ref for avro schema can be a schema list separated by `:` or `;`
- Will this be a breaking change?
No
- How could it be implemented/designed?
Schema parser could inline all resources by parsing from last schema to first e.g.
`a.avsc;common.avsc` would parse common.avsc and replace all type refs by looking at common.avsc

**Comment by michaelpro1** [comment]
Alternative for this change I saw mentioned in one of avro [JIRAs ](https://issues.apache.org/jira/browse/AVRO-1188)- basically to include an `imports` file array at top level however I am unclear how this could translate into JSON schema. 
Possibly just output a schema that contains a list of types (records) and force the AsyncAPI definition to specify the type that is referring to?

**Comment by fmvilas** [comment]
Thanks for commenting again, @michaelpro1. I totally missed this issue at first. I think what you're pointing to is a limitation of the Avro schema format specification and should be addressed by them. Just like JSON Schema provides `$ref`, Avro should provide their own mechanism.

Regarding the changes you propose, here's my feedback:

> Potentially the $ref for avro schema can be a schema list separated by : or ;

Hacking on `$ref` to add semantics would not be possible. `$ref` is defined to accept a valid URL and `:` or `;` are not valid URL characters. Making an exception here would be big hack just to solve a problem that's not of AsyncAPI but of Avro instead.

> Alternative for this change I saw mentioned in one of avro JIRAs - basically to include an imports file array at top level however I am unclear how this could translate into JSON schema.

This is not possible because the `imports` keyword is not part of the [Avro spec](https://avro.apache.org/docs/current/spec.html) but of the [Avro IDL](https://avro.apache.org/docs/1.9.2/idl.html), which are totally different things.

---

My suggestion is that you introduce some intermediate step to compile your Avro files into a single one with all the references resolved. Or maybe schema registries do this job already, I'm unsure.

Furthermore, open a Jira ticket on their side so they add this once and for all. I'll support you there as well.

**Comment by michaelpro1** [comment]
I was trying to use the schemas without a compiler, mainly to visualise topics + schemas from design. Doesn't look like there is anyway to do it with avro, even `.avpr` files do not support imports.

Schema registry would have been OK if it didn't require baked in credentials. Avro team in that ticket don't want to have any external reference either.

Oh well, that was just an idea.
